### ISSUE TITLE
0.2.0 Release please 

### ISSUE THREAD

**Issue by e1himself** [mpclarkson/icon-scraper#5]
Hi @mpclarkson
There's a fix that we would like to pull, but we try to avoid linking deps with `dev-master` reference.
Would you please be so kind to put a tag for next release? 

`0.2.0` probably?

**Comment by digitalbase** [comment]
@e1himself @mpclarkson jumping in this thread. Would be nice if you could review https://github.com/mpclarkson/icon-scraper/pull/6 and maybe get that in there too :-)

**Comment by mpclarkson** [comment]
Ok, sorry for the delay. On these issues now.

**Comment by mpclarkson** [comment]
Done.
